primefaces-framework/src/main/java/cz/vsmie/tomanek/primefaces/calendar/CalendarController.java
package cz.vsmie.tomanek.primefaces.calendar;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import lombok.Getter;
import lombok.Setter;
import lombok.val;

import org.primefaces.event.ScheduleEntryMoveEvent;
import org.primefaces.event.ScheduleEntryResizeEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.LazyScheduleModel;
import org.primefaces.model.ScheduleModel;

import cz.vsmie.tomanek.server.activity.ActivityLocal;
import cz.vsmie.tomanek.server.activity.shared.ActivityTO;
import cz.vsmie.tomanek.server.activity.shared.Priority;
import cz.vsmie.tomanek.server.util.Bean;

@ManagedBean(name = "scheduleController")
@ViewScoped
public class CalendarController implements Serializable {
	private static final long serialVersionUID = 1L;

	@Getter
	private ScheduleModel eventModel;

	@Getter
	@Setter
	private ActivityCalendarEvent event = new ActivityCalendarEvent(
			new ActivityTO());

	public CalendarController() {
		eventModel = new LazyScheduleModel() {
			private static final long serialVersionUID = 1L;

			@Override
			public void loadEvents(Date start, Date end) {
				val activities = Bean.get(ActivityLocal.class)
						.getAllActivities(start, end);

				for (val activity : activities) {
					super.addEvent(new ActivityCalendarEvent(activity));
				}
			}
		};
	}

	public String getPriority_() {
		if (event.getActivity().getPriority() == null) {
			return null;
		}
		return event.getActivity().getPriority().toString();
	}

	public void setPriority_(String priority) {
		this.event.getActivity().setPriority(Priority.valueOf(priority));
	}

	public Date getRandomDate(Date base) {
		Calendar date = Calendar.getInstance();
		date.setTime(base);
		date.add(Calendar.DATE, ((int) (Math.random() * 30)) + 1);
		return date.getTime();
	}

	public Date getInitialDate() {
		Calendar calendar = Calendar.getInstance();
		calendar.set(calendar.get(Calendar.YEAR), Calendar.FEBRUARY,
				calendar.get(Calendar.DATE), 0, 0, 0);

		return calendar.getTime();
	}

	public void addEvent(ActionEvent actionEvent) {
		val activity = Bean.get(ActivityLocal.class).saveActivity(
				event.getActivity());
		event.setActivity(activity);

		if (event.getId() == null)
			eventModel.addEvent(event);
		else
			eventModel.updateEvent(event);

		event = new ActivityCalendarEvent(new ActivityTO());
	}

	public void onEventSelect(SelectEvent selectEvent) {
		event = (ActivityCalendarEvent) selectEvent.getObject();
	}

	public void onDateSelect(SelectEvent selectEvent) {
		event = new ActivityCalendarEvent(new ActivityTO());
		event.setStartDate((Date) selectEvent.getObject());
		event.setEndDate((Date) selectEvent.getObject());
	}

	public void onEventMove(ScheduleEntryMoveEvent event) {
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO,
				"Event moved", "Day delta:" + event.getDayDelta()
						+ ", Minute delta:" + event.getMinuteDelta());

		addMessage(message);
	}

	public void onEventResize(ScheduleEntryResizeEvent event) {
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO,
				"Event resized", "Day delta:" + event.getDayDelta()
						+ ", Minute delta:" + event.getMinuteDelta());

		addMessage(message);
	}

	private void addMessage(FacesMessage message) {
		// testing purpose only
		// FacesContext.getCurrentInstance().addMessage(null, message);
	}

}

primefaces-framework/src/main/java/cz/vsmie/tomanek/primefaces/contact/ContactEditBean.java
package cz.vsmie.tomanek.primefaces.contact;

import java.io.IOException;
import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import lombok.Delegate;
import lombok.val;
import lombok.extern.log4j.Log4j;
import cz.vsmie.tomanek.server.contact.ContactLocal;
import cz.vsmie.tomanek.server.contact.shared.ContactTO;
import cz.vsmie.tomanek.server.util.Bean;

@ManagedBean(name = "ContactEditBean")
@ViewScoped
@Log4j
public class ContactEditBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Delegate
	private ContactTO contact;

	public ContactEditBean() {
		val param = FacesContext.getCurrentInstance().getExternalContext()
				.getRequestParameterMap();
		if (param.containsKey("id")) {
			try {
				val id = Long.parseLong(param.get("id"));
				this.contact = Bean.get(ContactLocal.class).getContact(id);
			} catch (NumberFormatException e) {
				log.debug("Id parameter: " + param.get("id")
						+ " is not valid for contact edit", e);
			}
		}
		if (contact == null) {
			contact = new ContactTO();
		}
	}

	public String save() {
		val saved = Bean.get(ContactLocal.class).save(contact);
		try {
			FacesContext.getCurrentInstance().getExternalContext()
					.redirect("contact-view.xhtml?id=" + saved.getId());
		} catch (IOException e) {
		}
		return "contact-view.xhtml?id=" + saved.getId();
	}

}

primefaces-framework/src/main/java/cz/vsmie/tomanek/primefaces/contact/ContactListBean.java
package cz.vsmie.tomanek.primefaces.contact;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import lombok.Getter;
import cz.vsmie.tomanek.server.contact.ContactLocal;
import cz.vsmie.tomanek.server.util.Bean;

@ManagedBean(name = "ContactListBean")
@ViewScoped
public class ContactListBean {

	@Getter
	private ContactLazyModel gridModel = new ContactLazyModel();


	public void delete(Long deleteId) {
		Bean.get(ContactLocal.class).remove(deleteId);
	}

}

primefaces-framework/src/main/webapp/calendar.xhtml
<?xml version="1.0"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:head />
	<h:body>
		<ui:composition template="template.xhtml">
			<ui:define name="content">
				<h:form id="form">

					<p:growl id="messages" showDetail="true" />

					<p:schedule id="schedule" value="#{scheduleController.eventModel}"
						widgetVar="myschedule" locale="cs">

						<p:ajax event="dateSelect"
							listener="#{scheduleController.onDateSelect}"
							update="eventDetails" oncomplete="eventDialog.show()" />
						<p:ajax event="eventSelect"
							listener="#{scheduleController.onEventSelect}"
							update="eventDetails" oncomplete="eventDialog.show()" />
						<p:ajax event="eventMove"
							listener="#{scheduleController.onEventMove}" update="messages" />
						<p:ajax event="eventResize"
							listener="#{scheduleController.onEventResize}" update="messages" />

					</p:schedule>

					<p:dialog widgetVar="eventDialog" header="Detail události"
						showEffect="clip" hideEffect="clip">
						<h:panelGrid id="eventDetails" columns="2">
							<h:outputLabel for="title" value="Titulek:" />
							<p:inputText id="title" value="#{scheduleController.event.title}"
								required="true" />

							<h:outputLabel for="note" value="Poznámka:" />
							<p:inputTextarea rows="5" id="note"
								value="#{scheduleController.event.note}" required="false" />

							<h:outputLabel for="priority" value="Priorita:" />
							<p:selectOneListbox id="priority" required="true"
								value="#{scheduleController.priority_}">
								<f:selectItem itemLabel="LOW" itemValue="LOW" />
								<f:selectItem itemLabel="MEDIUM" itemValue="MEDIUM" />
								<f:selectItem itemLabel="HIGHT" itemValue="HIGHT" />
							</p:selectOneListbox>


							<h:outputLabel for="from" value="Začátek:" />
							<p:calendar id="from" required="true"
								value="#{scheduleController.event.startDate}"
								pattern="MM/dd/yyyy HH:mm">
								<f:validator validatorId="twoDates" />
								<f:attribute name="otherDate"
									value="#{scheduleController.event.endDate}" />
							</p:calendar>

							<h:outputLabel for="to" value="Konec:" />
							<p:calendar id="to" value="#{scheduleController.event.endDate}"
								pattern="MM/dd/yyyy HH:mm" required="true" />

							<p:commandButton type="reset" value="Reset" />
							<p:commandButton id="addButton" value="Save"
								actionListener="#{scheduleController.addEvent}"
								oncomplete="if (!args.validationFailed) eventDialog.hide();if (!args.validationFailed) myschedule.update();" />
						</h:panelGrid>
					</p:dialog>
				</h:form>

			</ui:define>
		</ui:composition>
	</h:body>
</f:view>

primefaces-framework/src/main/webapp/contact-edit.xhtml
<?xml version="1.0"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:head />
	<h:body>
		<ui:composition template="template.xhtml">
			<ui:define name="content">
				<h:form id="form">
					<p:fieldset legend="Základní informace" toggleable="false">
						<p:panelGrid columns="4" style="width: 100%">
							<h:outputLabel for="firstname" value="Jméno:" />
							<p:inputText id="firstname" value="#{ContactEditBean.name}"
								required="true" label="Firstname" />

							<h:outputLabel for="surname" value="Příjmení:" />
							<p:inputText id="surname" value="#{ContactEditBean.surname}"
								required="true" label="Surname" />

							<h:outputLabel for="birthdate" value="Datum narození:" />
							<p:calendar value="#{ContactEditBean.birthday}" id="birthdate"
								showOn="button" />
						</p:panelGrid>
					</p:fieldset>

					<p:fieldset legend="Adresa" toggleable="true" toggleSpeed="500">
						<p:panelGrid columns="2" style="width: 100%">
							<h:outputLabel for="street" value="Ulice:" />
							<p:inputText id="street" value="#{ContactEditBean.street}"
								label="street" />
							<h:outputLabel for="city" value="Město:" />
							<p:inputText id="city" value="#{ContactEditBean.city}"
								label="city" />
							<h:outputLabel for="postCode" value="PSČ:" />
							<p:inputText id="postCode" value="#{ContactEditBean.postCode}"
								label="postCode" />
							<h:outputLabel for="country" value="Země:" />
							<p:inputText id="country" value="#{ContactEditBean.country}"
								label="country" />
						</p:panelGrid>
					</p:fieldset>
					<p:fieldset legend="Telefon / email" toggleable="true"
						toggleSpeed="500">
						<p:panelGrid columns="2" style="width: 100%">
							<h:outputLabel for="workPhone" value="Pracovní telefon:" />
							<p:inputText id="workPhone" value="#{ContactEditBean.workPhone}"
								label="workPhone" />
							<h:outputLabel for="privatePhone" value="Soukromý telefon:" />
							<p:inputText id="privatePhone"
								value="#{ContactEditBean.privatePhone}" label="privatePhone" />
							<h:outputLabel for="mobilePhone" value="Mobilní telefon:" />
							<p:inputText id="mobilePhone"
								value="#{ContactEditBean.mobilePhone}" label="mobilePhone" />
							<h:outputLabel for="primaryEmail" value="Primární email:" />
							<p:inputText id="primaryEmail"
								value="#{ContactEditBean.primaryEmail}" label="primaryEmail"
								required="true" />
							<h:outputLabel for="secondaryEmail" value="Sekundární email:" />
							<p:inputText id="secondaryEmail"
								value="#{ContactEditBean.secondaryEmail}" label="secondaryEmail" />
						</p:panelGrid>
					</p:fieldset>
					<p:fieldset legend="Poznámka" toggleable="true" toggleSpeed="500">
						<p:panelGrid columns="1">
							<p:inputTextarea rows="6" cols="33" />
						</p:panelGrid>
					</p:fieldset>
					<p:commandButton actionListener="#{ContactEditBean.save}"
						update="form" value="uložit" ajax="true" />
				</h:form>
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>

primefaces-framework/src/main/webapp/contact-list.xhtml
<?xml version="1.0"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:head />
	<h:body>
		<ui:composition template="template.xhtml">
			<ui:define name="content">
				<h:form id="form">
					<p:dataTable var="contact" value="#{ContactListBean.gridModel}"
						paginator="true" rows="15" id="carTable" lazy="true">

						<p:column headerText="Jméno">
							<h:outputText value="#{contact.name}" />
						</p:column>

						<p:column headerText="Příjmení">
							<h:outputText value="#{contact.surname}" />
						</p:column>

						<p:column headerText="Hlavní e-mail">
							<h:outputText value="#{contact.primaryEmail}" />
						</p:column>

						<p:column headerText="Pracovní telefon">
							<h:outputText value="#{contact.workPhone}" />
						</p:column>
						<p:column headerText="soukromý telefon">
							<h:outputText value="#{contact.privatePhone}" />
						</p:column>

						<p:column headerText="akce">
							<h:outputLink value="contact-view.xhtml">
								<h:outputText value="zobrazit" />
								<f:param name="id" value="#{contact.id}" />
							</h:outputLink>
							<h:outputText value=" " />
							<h:outputLink value="contact-edit.xhtml">
								<h:outputText value="upravit" />
								<f:param name="id" value="#{contact.id}" />
							</h:outputLink>
							<h:outputText value=" " />
							<p:commandLink action="#{ContactListBean.delete(contact.id)}"
								value="smazat" ajax="false">
							</p:commandLink>
						</p:column>

					</p:dataTable>
				</h:form>
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>

primefaces-framework/src/main/webapp/contact-view.xhtml
<?xml version="1.0"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:head />
	<h:body>
		<ui:composition template="template.xhtml">
			<ui:define name="content">
				<h:form id="form">
					<p:fieldset legend="Základní informace" toggleable="false">
						<p:panelGrid columns="4" style="width: 100%">
							<h:outputLabel for="firstname" value="Jméno:" />
							<h:outputText value="#{ContactEditBean.name}" />

							<h:outputLabel for="surname" value="Příjmení:" />
							<h:outputText id="surname" value="#{ContactEditBean.surname}" />

							<h:outputLabel for="birthdate" value="Datum narození:" />
							<h:outputText value="#{ContactEditBean.birthday}" />
						</p:panelGrid>
					</p:fieldset>

					<p:fieldset legend="Adresa" toggleable="true" toggleSpeed="500">
						<p:panelGrid columns="2" style="width: 100%">
							<h:outputLabel for="street" value="Ulice:" />
							<h:outputText id="street" value="#{ContactEditBean.street}" />
							<h:outputLabel for="city" value="Město:" />
							<h:outputText id="city" value="#{ContactEditBean.city}" />
							<h:outputLabel for="postCode" value="PSČ:" />
							<h:outputText id="postCode" value="#{ContactEditBean.postCode}" />
							<h:outputLabel for="country" value="Země:" />
							<h:outputText id="country" value="#{ContactEditBean.country}" />
						</p:panelGrid>
					</p:fieldset>

					<p:fieldset legend="Telefon / email" toggleable="true"
						toggleSpeed="500">
						<p:panelGrid columns="2" style="width: 100%">
							<h:outputLabel for="workPhone" value="Pracovní telefon:" />
							<h:outputText id="workPhone" value="#{ContactEditBean.workPhone}" />
							<h:outputLabel for="privatePhone" value="Soukromý telefon:" />
							<h:outputText id="privatePhone"
								value="#{ContactEditBean.privatePhone}" />
							<h:outputLabel for="mobilePhone" value="Mobilní telefon:" />
							<h:outputText id="mobilePhone"
								value="#{ContactEditBean.mobilePhone}" />
							<h:outputLabel for="primaryEmail" value="Primární email:" />
							<h:outputText id="primaryEmail"
								value="#{ContactEditBean.primaryEmail}" />
							<h:outputLabel for="secondaryEmail" value="Sekundární email:" />
							<h:outputText id="secondaryEmail"
								value="#{ContactEditBean.secondaryEmail}" />
						</p:panelGrid>
					</p:fieldset>
					<p:fieldset legend="Poznámka" toggleable="true" toggleSpeed="500">
						<p:panelGrid columns="1">
							<h:outputText value="#{ContactEditBean.note}" />
						</p:panelGrid>
					</p:fieldset>
				</h:form>
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>

primefaces-framework/src/main/webapp/template.xhtml
<?xml version="1.0"?>

<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:head />
	<h:body style="font-size:80%;">
		<p:layout fullPage="true">

			<p:layoutUnit position="north" size="50" resizable="false"
				closable="false" collapsible="false">
				<h:outputText value="PrimeFaces framework" />
			</p:layoutUnit>

			<p:layoutUnit position="west" size="200" header="Navigace"
				resizable="true" closable="true" collapsible="true">
				<h:form id="menuform">
					<p:menu>
						<p:menuitem value="Nový kontakt" url="contact-edit.xhtml" />
						<p:menuitem value="Seznam kontaktů" url="contact-list.xhtml" />
						<p:menuitem value="Kalendář" url="calendar.xhtml" />
					</p:menu>
				</h:form>
			</p:layoutUnit>


			<p:layoutUnit position="center">
				<ui:insert name="content">
				</ui:insert>
			</p:layoutUnit>

		</p:layout>
	</h:body>
</f:view>

primefaces-framework/src/main/webapp/view.xhtml
<?xml version="1.0"?>

<f:view
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
>
	<h:head />
	<h:body>
		<h:outputText value="#{i18n['primefaces-framework-hello-world']}" />
	</h:body>
</f:view>